---
title: Daily Miscellany
timezone: America/Chicago
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    link: ''
    source: ''
theme: jekyll-theme-cayman
author: Ken Booth
description: Sometimes Updated Daily
baseurl: "/"
url: https://dailymiscellany.com/
lang: en
exclude:
- README.md
- CHANGELOG.md
google_analytics:
paginate: 10
