title: Daily Miscellany
theme: jekyll-theme-cayman
author: Ken Booth author
description: Sometimes Updated Daily
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://dailymiscellany.com/" # the base hostname & protocol for your site, e.g. http://example.com
lang: en
timezone: America/Chicago
exclude:
 - README.md
 - CHANGELOG.md
google_analytics:
paginate: 10
